name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential wx-common libwxgtk3.2-dev

      - name: Build plugin
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload plugin binary
        uses: actions/upload-artifact@v4
        with:
          name: simple_belfast_pi-linux
          path: build/src/libsimple_belfast_pi.so
