name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential wx-common libwxgtk3.2-dev

      - name: Clone OpenCPN headers
        run: |
          git clone --depth=1 https://github.com/OpenCPN/OpenCPN.git ../OpenCPN

      - name: Build plugin
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Package plugin as .tar.gz
        run: |
          mkdir -p package/simple_belfast_pi
          cp build/src/libsimple_belfast_pi.so package/simple_belfast_pi/
          cp metadata.xml package/simple_belfast_pi/
          cd package
          tar -czf ../simple_belfast_pi.tar.gz simple_belfast_pi


      - name: Upload plugin binary
        uses: actions/upload-artifact@v4
        with:
          name: simple_belfast_pi-linux
          path: build/src/libsimple_belfast_pi.so

      - name: Upload installable plugin tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: simple_belfast_pi-installable
          path: simple_belfast_pi.tar.gz
